package cn.iimedia.jb.http.bean

/**
 * Created by iiMedia on 2018/6/12.
 */

data class InfoListData(
        val baseCatNo: Int,
        val pubTime: String,
        val summary: String,
        val replyCount: Int,
        val lastUpdateTime: String,
        val no: Int,
        val readCount: Int,
        val investmentAgencies: String,
        val pageWord: Int,
        val hiddenFlagStr: String,
        val recommended: String,
        val thirdCatNo: Int,
        val payCount: Int,
        val columnId: Int,
        val picNum: Int,
        val coverImgSafe: String,
        val attachFileSize: Int,
        val interview_figure_id: Int,
        val subCatNo: Int,
        val amount: String,
        val author: String,
        val title: String,
        val coverImg: String,
        val words: Int,
        val priority: Int,
        val readWeekCount: Int,
        val industry: String,
        val attachTitle: String,
        val credit: Int,
        val sourceAddress: String,
        val memberNo: Int,
        val eventime: String,
        val keywords: String,
        val hiddenFlag: Int,
        val purenessContent: String,
        val sourceText: String,
        val replaceContent: String,
        val readMonthCount: Int,
        val lastReplyTime: String,
        val content: String,
        val parentCatNo: Int,
        val exclusiveTag: Int,
        val flv: String,
        val company: String,
        val lastReplyNo: Int,
        val fromHTML: String,
        val attachFile: String,
        val read48HourCount: Int
)
